SENSOR_COLUMNS = [
    "pm_1_1",
    "pm_1_2",
    "pm_1_3",
    "pm_2_1",
    "pm_2_2",
    "pm_2_3",
    "pm_3_1",
    "pm_3_2",
    "pm_3_3",
]

REFERENCE_COLUMN = "reference_pm_after"

COLUMNS = [
    "APMdatetime",
    "RPMdatetime",
    "reference_pm_before",
    "reference_pm_after",
    "rpm_1_1",
    "rpm_1_2",
    "rpm_1_3",
    "rpm_2_1",
    "rpm_2_2",
    "rpm_2_3",
    "rpm_3_1",
    "rpm_3_2",
    "rpm_3_3",
    "npm",
    "pm_1_1",
    "pm_1_2",
    "pm_1_3",
    "pm_2_1",
    "pm_2_2",
    "pm_2_3",
    "pm_3_1",
    "pm_3_2",
    "pm_3_3",
    "temperature",
    "humidity",
    "O3",
    "CO",
    "NO2",
    "SO2",
    "wind_direction",
    "wind_speed",
]
